server:
  port: 5002
spring:
  application:
    name: site

humansite:
  credentials:
    username: ML17934
    password: 5314Humansite
  base-url: "https://ahr.humansite.com.mx"
  download-dir: "pdf"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
